### PR TITLE
Update action to use YamlCreate from the fork + LICENSE

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
Signed-off-by: Vedant <83997633+vedantmgoyal2009@users.noreply.github.com>

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
cc @john-preston

**Comment by vedantmgoyal2009** [comment]
cc @john-preston @ilya-fedin

**Comment by vedantmgoyal2009** [comment]
cc @john-preston @ilya-fedin

**Comment by john-preston** [comment]
Ok.

**Pull request merged**
